{
 "title": "Kyverno pod alerts",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Nirmata-system Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"nirmata-system\"}[5m])) by (pod)\r\n#CPU usage for every pods in kyverno namespace",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not Ready State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kube_pod_status_ready{condition=\"false\",namespace=\"nirmata-system\"}\r\n#Pods that are not in ready state",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"nirmata-system\"}) by (pod)\r\n#Memory usage for every pods in kyverno namespace",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CrashLoopBackOff Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{reason=\"CrashLoopBackOff\",namespace=\"nirmata-system\"}\r\n#Pods that are in CrashLoopBackOff State",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Kyverno namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"kyverno\"}[5m])) by (pod)\r\n#CPU usage for every pods in kyverno namespace",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not Ready State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "kube_pod_status_ready{condition=\"false\",namespace=\"kyverno\"}\r\n#Pods that are not in ready state",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"kyverno\"}) by (pod)\r\n#Memory usage for every pods in kyverno namespace",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CrashLoopBackOff Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{reason=\"CrashLoopBackOff\",namespace=\"kyverno\"}\r\n#Pods that are in CrashLoopBackOff State",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}