# Ubuntu 16.04 Image

FROM kubevirt/registry-disk-v1alpha

LABEL maintainer="Nirmata <brandon@nirmata.com>"

# Add Ubuntu 16.04 cloud disk image
RUN curl -g -L http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img  > /disk/ubuntu1604.qcow2
