apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Ubuntu 16.04 Desktop
    iconClass: icon-ubuntu
    tags: kubevirt,ocp,template,linux,virtualmachine
  creationTimestamp: null
  labels:
    kubevirt.io/os: ubuntu1604
    miq.github.io/kubevirt-is-vm-template: "true"
  name: vm-template-ubuntu1604
objects:
- apiVersion: kubevirt.io/v1alpha2
  kind: VirtualMachine
  metadata:
    creationTimestamp: null
    labels:
      kubevirt-vm: vm-${NAME}
      kubevirt.io/os: ubuntu1604
    name: ${NAME}
  spec:
    running: false
    template:
      metadata:
        creationTimestamp: null
        labels:
          kubevirt-vm: vm-${NAME}
          kubevirt.io/os: ubuntu1604
      spec:
        domain:
          cpu:
            cores: ${{CPU_CORES}}
          devices:
            disks:
            - disk:
                bus: virtio
              name: registrydisk
              volumeName: registryvolume
            - disk:
                bus: virtio
              name: cloudinitdisk
              volumeName: cloudinitvolume
          machine:
            type: ""
          resources:
            requests:
              memory: ${MEMORY}
        terminationGracePeriodSeconds: 0
        volumes:
        - name: registryvolume
          registryDisk:
            image: registry:5000/kubevirt/ubuntu1604:devel
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: ubuntu
              chpasswd: { expire: False }
          name: cloudinitvolume
  status: {}
parameters:
- description: Name for the new VM
  name: ubuntu1604desktop
- description: Amount of memory
  name: MEMORY
  value: 4096Mi
- description: Amount of cores
  name: CPU_CORES
  value: "4"
