---
apiVersion: "rbac.authorization.k8s.io/v1beta1"
kind: "ClusterRoleBinding"
metadata:
  namespace: "nirmata"
  name: "nirmata-test-crb"
  labels: {}
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "ClusterRole"
  name: "nirmata-test-cr"
subjects:
- kind: "ServiceAccount"
  name: "nirmata-test-sa"
  namespace: "nirmata"
