---
apiVersion: "rbac.authorization.k8s.io/v1beta1"
kind: "RoleBinding"
metadata:
  namespace: "nirmata"
  name: "nirmata-test-rb"
  labels: {}
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "Role"
  name: "nirmata-test-role"
subjects:
- kind: "ServiceAccount"
  name: "nirmata-test-sa"
  namespace: "nirmata"
